<?php

declare(strict_types=1);

return [
    'content' => [
        'profile' => [
            'name' => 'Wrandell I. Almeda',
            'initials' => 'WA',
            'title' => 'Technical Support Engineer',
            'location' => 'Quezon City, Philippines',
            'email' => 'wrandellalmeda@gmail.com',
            'phoneDisplay' => '+63 976 178 4601',
            'phoneHref' => '+639761784601',
            'positioning' => 'Technical Support Engineer building reliable, user-focused, and modern technology solutions.',
            'valueProposition' => 'I help users, teams, and organizations resolve technical issues, improve support processes, maintain clear documentation, and implement dependable web and cloud-related solutions.',
            'heroSupport' => 'Technical Support Engineer with experience in troubleshooting, end-user assistance, ticket handling, web systems, documentation, system testing, and cloud-related support.',
            'availability' => 'Available for professional opportunities',
            'linkedInUrl' => '',
            'githubUrl' => '',
            'bookingUrl' => '',
        ],
        'roleLabels' => [
            'Technical Support Engineer',
            'Web Developer',
            'IT Support Professional',
            'Cloud Support Professional',
        ],
        'about' => [
            'heading' => 'Technical support grounded in clear communication and practical problem-solving.',
            'paragraphs' => [
                'Wrandell I. Almeda is a Technical Support Engineer with experience in IT support, customer service, troubleshooting, ticket handling, documentation, and end-user assistance. He supports users by analyzing incidents, coordinating resolutions, assisting with system testing and configuration updates, and communicating clearly with both users and technical teams.',
                'His background also includes website development, cloud-related support, DNS and SSL configuration, deployment checks, email configuration, and file storage integration. He approaches technical problems with patience, structured analysis, clear documentation, and a strong focus on the user experience.',
            ],
            'highlights' => [
                'Technical issue analysis and resolution',
                'End-user and client support',
                'Ticket monitoring and documentation',
                'Web and cloud support',
                'System testing and deployment assistance',
                'Cross-team coordination',
            ],
        ],
        'experiences' => [
            [
                'role' => 'Technical Support Engineer',
                'organization' => 'Valueline Systems & Solutions Corp.',
                'location' => 'Quezon City, Philippines',
                'dates' => 'June 2, 2025 – Present',
                'responsibilities' => [
                    'Provide technical support for users and clients',
                    'Analyze, troubleshoot, and track technical issues',
                    'Manage ticket updates and status monitoring',
                    'Maintain support documentation',
                    'Coordinate with development and operations teams',
                    'Assist with system testing and configuration updates',
                    'Perform deployment checks',
                    'Support platform improvements',
                    'Assist with DNS, SSL, email configuration, and file storage integration when required',
                ],
            ],
            [
                'role' => 'Customer Representative',
                'organization' => 'Alorica',
                'location' => 'Quezon City, Philippines',
                'dates' => 'January 2025 – May 2025',
                'responsibilities' => [
                    'Managed customer inquiries and account concerns',
                    'Addressed service-related issues',
                    'Communicated clearly and empathetically with customers',
                    'Documented interactions accurately',
                    'Escalated cases requiring additional assistance',
                ],
            ],
            [
                'role' => 'Technical Support',
                'organization' => 'WIB Outsourcing Inc.',
                'location' => 'Quezon City, Philippines',
                'dates' => 'November 2023 – January 2025',
                'responsibilities' => [
                    'Provided technical troubleshooting guidance',
                    'Assisted customers across assigned support concerns',
                    'Maintained clear issue documentation',
                    'Supported proper case follow-up until resolution',
                ],
            ],
            [
                'role' => 'Technical Support Intern',
                'organization' => 'National Bureau of Investigation',
                'location' => 'Ali Mall, Cubao, Quezon City, Philippines',
                'dates' => 'April 2023 – July 2023',
                'responsibilities' => [
                    'Assisted users with technical concerns',
                    'Provided basic device and software support',
                    'Helped with data handling',
                    'Supported technical documentation',
                ],
            ],
        ],
        'skillGroups' => [
            ['name' => 'Web Development', 'skills' => ['PHP', 'HTML', 'CSS', 'JavaScript']],
            ['name' => 'Version Control and Development', 'skills' => ['Git', 'GitHub']],
            ['name' => 'Infrastructure and Cloud', 'skills' => ['Docker', 'AWS fundamentals', 'Cloudflare DNS']],
            ['name' => 'Databases', 'skills' => ['PostgreSQL fundamentals', 'MySQL fundamentals']],
            ['name' => 'Technical Support', 'skills' => ['Technical troubleshooting', 'End-user support', 'Ticket handling', 'Issue documentation', 'Network and device fundamentals', 'Team collaboration', 'System testing', 'Deployment checks']],
            ['name' => 'AI-Assisted Development Tools', 'skills' => ['OpenAI Codex', 'Claude', 'ChatGPT', 'DeepSeek', 'GitHub Copilot']],
        ],
        'certifications' => [
            ['name' => 'AWS Certified Cloud Practitioner', 'issuer' => 'Amazon Web Services', 'issueYear' => '', 'credentialId' => '', 'verificationUrl' => '', 'badgeImage' => '', 'badgeAlt' => '', 'featured' => true],
            ['name' => 'AWS Certified Solutions Architect – Associate', 'issuer' => 'Amazon Web Services', 'issueYear' => '', 'credentialId' => '', 'verificationUrl' => '', 'badgeImage' => '', 'badgeAlt' => '', 'featured' => true],
            ['name' => 'Veeam Technical Specialist – Off-site Backup Service Provider', 'issuer' => 'Veeam', 'issueYear' => '2025', 'credentialId' => '', 'verificationUrl' => '', 'badgeImage' => '', 'badgeAlt' => '', 'featured' => true],
        ],
        'education' => [
            'degree' => 'Bachelor of Science in Information Technology',
            'institution' => 'Eulogio “Amang” Rodriguez Institute of Science and Technology',
            'graduationYear' => '2023',
        ],
        'processSteps' => [
            ['title' => 'Understand', 'description' => 'Gather the user’s concern, system context, symptoms, and expected behavior.'],
            ['title' => 'Analyze', 'description' => 'Review available evidence, reproduce the issue where possible, and isolate likely causes.'],
            ['title' => 'Troubleshoot', 'description' => 'Test appropriate solutions methodically without introducing unnecessary changes.'],
            ['title' => 'Coordinate', 'description' => 'Work with users, developers, operations teams, or other stakeholders when escalation is required.'],
            ['title' => 'Validate', 'description' => 'Confirm that the issue is resolved and that the expected behavior has been restored.'],
            ['title' => 'Document', 'description' => 'Record the issue, actions taken, outcome, and relevant follow-up information.'],
        ],
        'strengths' => [
            'Clear technical communication',
            'Patient end-user assistance',
            'Structured troubleshooting',
            'Accurate documentation',
            'Cross-team collaboration',
            'Practical web development knowledge',
            'Cloud and DNS fundamentals',
            'Customer service experience',
            'Willingness to learn and improve',
            'Attention to issue follow-through',
        ],
        'projectFilters' => [
            'All Projects',
            'Support Systems',
            'Web Development',
            'Business Systems',
            'Internal Tools',
            'UI Improvements',
        ],
    ],
    'projects' => [
        ['id' => 'ticketing-system', 'title' => 'Ticketing System', 'category' => 'Support Systems', 'summary' => 'An example workspace for receiving, prioritizing, tracking, and documenting support requests.', 'preview_image' => '/images/projects/ticketing-concept.svg', 'preview_alt' => 'Concept interface showing a support ticket queue and active conversation workspace'],
        ['id' => 'attendance-management-qr', 'title' => 'Attendance Management System Using QR Code', 'category' => 'Internal Tools', 'summary' => 'An example attendance experience combining QR check-in, daily status, and record review.', 'preview_image' => '/images/projects/attendance-concept.svg', 'preview_alt' => 'Concept interface showing a QR attendance scanner and daily attendance records'],
        ['id' => 'website-revamping', 'title' => 'Website Revamping', 'category' => 'UI Improvements', 'summary' => 'An example redesign direction focused on clearer hierarchy, responsive layouts, and simpler navigation.', 'preview_image' => '/images/projects/revamp-concept.svg', 'preview_alt' => 'Concept comparison showing a website layout before and after a modern redesign'],
        ['id' => 'hotel-management', 'title' => 'Hotel Management System', 'category' => 'Business Systems', 'summary' => 'An example operations view for room availability, reservations, guest records, and check-in status.', 'preview_image' => '/images/projects/hotel-concept.svg', 'preview_alt' => 'Concept interface showing room availability and hotel reservation management'],
        ['id' => 'point-of-sale', 'title' => 'Point-of-Sale System', 'category' => 'Business Systems', 'summary' => 'An example checkout workflow with product browsing, cart review, totals, and payment status.', 'preview_image' => '/images/projects/pos-concept.svg', 'preview_alt' => 'Concept point-of-sale interface showing products, a cart, and checkout totals'],
    ],
];
